site_name: Hephaestus Documentation
site_url: https://example.org/hephaestus
site_description: Hephaestus is a self-improving code generation system
site_author: Hephaestus Team

repo_name: hephaestus
repo_url: https://github.com/organization/hephaestus

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    logo: material/robot
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true

nav:
  - Home: index.md
  - Concepts:
    - Overview: concepts/index.md
    - Architecture: concepts/architecture.md
    - Flow Engine: concepts/flow_engine.md
    - Nodes: concepts/nodes.md
  - Guides:
    - Overview: guides/index.md
    - Getting Started: guides/getting_started.md
    - Troubleshooting: guides/troubleshooting.md
  - Reference:
    - Overview: reference/index.md
    - API Reference: reference/api.md
    - Configuration: reference/configuration.md
  - Development:
    - Overview: development/index.md
  - About:
    - Overview: about/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/organization/hephaestus
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hephaestus_ai

copyright: Copyright &copy; 2025 Hephaestus Team 